package:
  authors:
    - Tatsuya Koishi
  description: ginseng PieFed libraries
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/ginseng-piefed
  version: 0.1.0
piefed:
  api:
    version: alpha
  community:
    types:
      - Subscribed
      - Moderating
  hosts:
    default: pf.korako.me
  subject:
    max_length: 50
